/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface_Sub;

import DB.ComandosSQL;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Gu
 */
public class Interface_Pesquisa extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Pesquisa
     */
    public Interface_Pesquisa() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        text_pesquisa.setEditable(true);
        text_pesquisa.setText("Digite aqui para pesquisar");
        text_pesquisa.setForeground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        text_pesquisa = new javax.swing.JTextField();
        botao_pesquisar = new javax.swing.JButton();
        botao_fechar = new javax.swing.JButton();
        tabela_pesquisa = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_pesquisa_uni = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_pesquisa_proj = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_pesquisa_inv = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_pesquisa_fol = new javax.swing.JTable();
        radio_uni = new javax.swing.JRadioButton();
        radio_proj = new javax.swing.JRadioButton();
        radio_inv = new javax.swing.JRadioButton();
        radio_fol = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_pesquisaMouseClicked(evt);
            }
        });

        botao_pesquisar.setText("Pesquisar");
        botao_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesquisarActionPerformed(evt);
            }
        });

        botao_fechar.setText("Fechar");
        botao_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_fecharActionPerformed(evt);
            }
        });

        table_pesquisa_uni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Login", "Nascimento", "Dia"
            }
        ){
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int lin, int col) {
                return false;
            }

        }
    );
    table_pesquisa_uni.setColumnSelectionAllowed(true);
    jScrollPane2.setViewportView(table_pesquisa_uni);
    table_pesquisa_uni.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    tabela_pesquisa.addTab("Universitários", jScrollPane2);

    table_pesquisa_proj.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Código", "Nome", "Organizador", "Inicio", "Fim"
        }
    ){
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int lin, int col) {
            return false;
        }

    });
    jScrollPane3.setViewportView(table_pesquisa_proj);

    tabela_pesquisa.addTab("Projetos", jScrollPane3);

    table_pesquisa_inv.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Código Material", "Descrição", "Quantidade", "Medida", "Última Modificação"
        }
    ){
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int lin, int col) {
            return false;
        }

    });
    jScrollPane4.setViewportView(table_pesquisa_inv);

    tabela_pesquisa.addTab("Inventário", jScrollPane4);

    table_pesquisa_fol.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},

            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Nº Sequência", "Nome", "Data da Folga", "Data da Inclusão"
        }
    ){
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int lin, int col) {
            return false;
        }

    });
    jScrollPane5.setViewportView(table_pesquisa_fol);

    tabela_pesquisa.addTab("Folgas", jScrollPane5);

    buttonGroup1.add(radio_uni);
    radio_uni.setText("Universitário");

    buttonGroup1.add(radio_proj);
    radio_proj.setText("Projeto");

    buttonGroup1.add(radio_inv);
    radio_inv.setText("Inventário");

    buttonGroup1.add(radio_fol);
    radio_fol.setText("Folga");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(text_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(botao_pesquisar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botao_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(radio_uni)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(radio_proj)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(radio_inv)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(radio_fol)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabela_pesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(13, 13, 13)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(text_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botao_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botao_fechar))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radio_uni)
                .addComponent(radio_proj)
                .addComponent(radio_inv)
                .addComponent(radio_fol))
            .addContainerGap(239, Short.MAX_VALUE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addComponent(tabela_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesquisarActionPerformed
        ComandosSQL sql = new ComandosSQL();
        
        limpar_tabela();
        
        if (radio_uni.isSelected() == true){
            try {
                sql.search_uni(text_pesquisa.getText(), table_pesquisa_uni);
                tabela_pesquisa.setSelectedIndex(0);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Interface_Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Interface_Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (radio_proj.isSelected() == true){
            try {
                sql.search_proj(text_pesquisa.getText(), table_pesquisa_proj);
                tabela_pesquisa.setSelectedIndex(1);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Interface_Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Interface_Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (radio_inv.isSelected() == true){
            try {
                sql.search_inv(text_pesquisa.getText(), table_pesquisa_inv);
                tabela_pesquisa.setSelectedIndex(2);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Interface_Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Interface_Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (radio_fol.isSelected() == true){
            try {
                sql.search_fol(text_pesquisa.getText(), table_pesquisa_fol);
                tabela_pesquisa.setSelectedIndex(3);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Interface_Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Interface_Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_botao_pesquisarActionPerformed

    private void botao_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_botao_fecharActionPerformed

    private void text_pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_pesquisaMouseClicked
        text_pesquisa.setText(null);
    }//GEN-LAST:event_text_pesquisaMouseClicked

    public void limpar_tabela(){
        for (int linha = 0; linha < 30 ; linha++){
            for (int coluna = 0 ; coluna < 5; coluna++){
                table_pesquisa_uni.setValueAt(null, linha, coluna);
            }
        }
        for (int linha = 0; linha < 30 ; linha++){
            for (int coluna = 0 ; coluna < 5; coluna++){
                table_pesquisa_proj.setValueAt(null, linha, coluna);
            }
        }
        for (int linha = 0; linha < 30 ; linha++){
            for (int coluna = 0 ; coluna < 5; coluna++){
                table_pesquisa_inv.setValueAt(null, linha, coluna);
            }
        }
        for (int linha = 0; linha < 30 ; linha++){
            for (int coluna = 0 ; coluna < 4; coluna++){
                table_pesquisa_fol.setValueAt(null, linha, coluna);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Pesquisa().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_fechar;
    private javax.swing.JButton botao_pesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton radio_fol;
    private javax.swing.JRadioButton radio_inv;
    private javax.swing.JRadioButton radio_proj;
    private javax.swing.JRadioButton radio_uni;
    private javax.swing.JTabbedPane tabela_pesquisa;
    private javax.swing.JTable table_pesquisa_fol;
    private javax.swing.JTable table_pesquisa_inv;
    private javax.swing.JTable table_pesquisa_proj;
    private javax.swing.JTable table_pesquisa_uni;
    private javax.swing.JTextField text_pesquisa;
    // End of variables declaration//GEN-END:variables

    public void setar_uni(String objeto, int linha, int coluna) {
        System.out.println("estrou setar uni\n"
                + "texto: "+objeto+", linha"+linha+", coluna: "+coluna);
        
        table_pesquisa_uni.setValueAt("testando2", 0, 0);
        
        System.out.println("saiu setar uni");
    }
}
