package Interface;

import DB.ComandosSQL;
import DB.MySQL;
import Interface_Sub.Add_Folgas;
import Interface_Sub.Add_Projeto;
import Interface_Sub.Add_Universitario;
import Interface_Sub.Edit_Folga;
import Interface_Sub.Edit_Inventario;
import Interface_Sub.Edit_Projeto;
import Interface_Sub.Edit_Universitario;
import Interface_Sub.Interface_Pesquisa;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Inicio extends JFrame {

    MySQL db = new MySQL("localhost", "iescola", "root", "");
    ComandosSQL comandos = new ComandosSQL();

    String uni_id, uni_nome, uni_escola, uni_faculdade, uni_dia;
    String proj_id, proj_nome, proj_organizador, proj_inicio, proj_fim;
    String folga_id, folga_data, folga_inclusao, folga_iduni, folga_escola;

    String query, id, nome, login, dia, nasc, codigo, coordenador, inicio, fim;
    int result, indiceDeTabela = 0, i = 0;
    boolean Double_Clik = false;
    ResultSet rs;

    /**
     * ***** PESQUISAR ****************
     */
    boolean pesquisa = false;
    String nomePesquisa;

    /**
     * ********************************
     */
    public void Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setVisible(true);
        Tabela.setEnabledAt(0, false);              //Desabilita a aba 0
        Tabela.setEnabledAt(1, false);              //Desabilita a aba 1
        Tabela.setEnabledAt(2, false);              //Desabilita a aba 2
        Tabela.setEnabledAt(3, false);              //Desabilita a aba 3
        //Tabela.setBackgroundAt(1, Color.BLUE);    //Muda cor da aba

        table_universitario.isCellEditable(0, 0);

    }

    private String formatData(Date dataHora) throws SQLException {
        Date nasci = dataHora;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String nascimento = formato.format(nasci);
        return nascimento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        botao_Adicionar = new javax.swing.JButton();
        botao_Editar = new javax.swing.JButton();
        botao_Pesquisar = new javax.swing.JButton();
        botao_Salvar = new javax.swing.JButton();
        botao_Excluir = new javax.swing.JButton();
        Tabela = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_universitario = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_Projetos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_escola = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_Folgas = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        btn_add_uni = new javax.swing.JMenuItem();
        btn_add_facul = new javax.swing.JMenuItem();
        btn_add_escola = new javax.swing.JMenuItem();
        btn_add_proj = new javax.swing.JMenuItem();
        btn_add_folga = new javax.swing.JMenuItem();
        btn_add_coord = new javax.swing.JMenuItem();
        btn_Adm = new javax.swing.JMenuItem();
        btn_calend = new javax.swing.JMenuItem();
        btn_senha = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        btn_uni = new javax.swing.JMenuItem();
        btn_facul = new javax.swing.JMenuItem();
        btn_escola = new javax.swing.JMenuItem();
        btn_proj = new javax.swing.JMenuItem();
        btn_fol = new javax.swing.JMenuItem();
        btn_coord = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        btn_sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escola da Família");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new 
            ImageIcon(getClass().getResource("/Imagens/icone.png")).getImage());
        setResizable(false);

        botao_Adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Mais.png"))); // NOI18N
        botao_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_AdicionarActionPerformed(evt);
            }
        });

        botao_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Editar.png"))); // NOI18N
        botao_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_EditarActionPerformed(evt);
            }
        });

        botao_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        botao_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_PesquisarActionPerformed(evt);
            }
        });

        botao_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        botao_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_SalvarActionPerformed(evt);
            }
        });

        botao_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Deletar.png"))); // NOI18N
        botao_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ExcluirActionPerformed(evt);
            }
        });

        table_universitario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Dia", "Escola", "Faculdade"
            }
        ){
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int lin, int col) {
                return false;
            }

        }
    );
    table_universitario.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_universitarioMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(table_universitario);

    Tabela.addTab("Universitários", jScrollPane2);

    table_Projetos.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Código", "Nome", "Organizador", "Inicio", "Fim"
        }
    ){
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int lin, int col) {
            return false;
        }

    });
    table_Projetos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_ProjetosMouseClicked(evt);
        }
    });
    jScrollPane3.setViewportView(table_Projetos);

    Tabela.addTab("Projetos", jScrollPane3);

    table_escola.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null}
        },
        new String [] {
            "ID Escola", "Nome", "Coordenador"
        }
    ){
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int lin, int col) {
            return false;
        }

    });
    table_escola.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_escolaMouseClicked(evt);
        }
    });
    jScrollPane4.setViewportView(table_escola);

    Tabela.addTab("Escolas", jScrollPane4);

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},

            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Nº Sequência", "Nome", "Escola", "Data da Folga", "Data da Inclusão"
        }
    ){
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int lin, int col) {
            return false;
        }

    });
    jScrollPane1.setViewportView(jTable1);

    Tabela.addTab("Faculdade", jScrollPane1);

    table_Folgas.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},

            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Nº Sequência", "Nome", "Escola", "Data da Folga", "Data da Inclusão"
        }
    ){
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int lin, int col) {
            return false;
        }

    });
    table_Folgas.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_FolgasMouseClicked(evt);
        }
    });
    jScrollPane5.setViewportView(table_Folgas);

    Tabela.addTab("Folgas", jScrollPane5);

    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},

            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Nº Sequência", "Nome", "Escola", "Data da Folga", "Data da Inclusão"
        }
    ){
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int lin, int col) {
            return false;
        }

    });
    jScrollPane6.setViewportView(jTable2);

    Tabela.addTab("Coordenador", jScrollPane6);

    jMenu1.setText("Arquivo");

    jMenu5.setText("Adicionar");

    btn_add_uni.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
    btn_add_uni.setText("Universitário");
    btn_add_uni.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_add_uniActionPerformed(evt);
        }
    });
    jMenu5.add(btn_add_uni);

    btn_add_facul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
    btn_add_facul.setText("Faculdade");
    btn_add_facul.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_add_faculActionPerformed(evt);
        }
    });
    jMenu5.add(btn_add_facul);

    btn_add_escola.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
    btn_add_escola.setText("Escola");
    jMenu5.add(btn_add_escola);

    btn_add_proj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
    btn_add_proj.setText("Projeto");
    btn_add_proj.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_add_projActionPerformed(evt);
        }
    });
    jMenu5.add(btn_add_proj);

    btn_add_folga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK));
    btn_add_folga.setText("Folga");
    btn_add_folga.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_add_folgaActionPerformed(evt);
        }
    });
    jMenu5.add(btn_add_folga);

    btn_add_coord.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
    btn_add_coord.setText("Coordenador");
    jMenu5.add(btn_add_coord);

    jMenu1.add(jMenu5);

    btn_Adm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
    btn_Adm.setText("Administrador");
    btn_Adm.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_AdmActionPerformed(evt);
        }
    });
    jMenu1.add(btn_Adm);

    btn_calend.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
    btn_calend.setText("Calendário");
    jMenu1.add(btn_calend);

    btn_senha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    btn_senha.setText("Alterar Senha");
    jMenu1.add(btn_senha);
    jMenu1.add(jSeparator1);

    jMenuItem8.setText("Sair");
    jMenu1.add(jMenuItem8);

    jMenuBar1.add(jMenu1);

    jMenu6.setText("Visualizar");

    btn_uni.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
    btn_uni.setText("Universitário");
    btn_uni.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_uniActionPerformed(evt);
        }
    });
    jMenu6.add(btn_uni);

    btn_facul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
    btn_facul.setText("Faculdade");
    jMenu6.add(btn_facul);

    btn_escola.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
    btn_escola.setText("Escola");
    btn_escola.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_escolaActionPerformed(evt);
        }
    });
    jMenu6.add(btn_escola);

    btn_proj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
    btn_proj.setText("Projeto");
    btn_proj.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_projActionPerformed(evt);
        }
    });
    jMenu6.add(btn_proj);

    btn_fol.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
    btn_fol.setText("Folga");
    btn_fol.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_folActionPerformed(evt);
        }
    });
    jMenu6.add(btn_fol);

    btn_coord.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
    btn_coord.setText("Coordenador");
    jMenu6.add(btn_coord);

    jMenuBar1.add(jMenu6);

    jMenu2.setText("Links");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Ajuda");

    btn_sobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
    btn_sobre.setText("Sobre");
    btn_sobre.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_sobreActionPerformed(evt);
        }
    });
    jMenu3.add(btn_sobre);

    jMenuBar1.add(jMenu3);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSeparator2)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(botao_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botao_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botao_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botao_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botao_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 293, Short.MAX_VALUE))
                .addComponent(Tabela))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(botao_Adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_Pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Tabela, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
            .addContainerGap())
    );

    table_universitario.setVisible(false);
    table_Projetos.setVisible(false);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_AdicionarActionPerformed
        Choose escolha = new Choose();
        escolha.setVisible(true);
    }//GEN-LAST:event_botao_AdicionarActionPerformed

    private void botao_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_PesquisarActionPerformed
        Interface_Sub.Interface_Pesquisa pesquisar = new Interface_Pesquisa();
        pesquisar.setVisible(true);
    }//GEN-LAST:event_botao_PesquisarActionPerformed

    private void botao_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_SalvarActionPerformed

    }//GEN-LAST:event_botao_SalvarActionPerformed

    private void btn_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sobreActionPerformed
        ComandosSQL b = new ComandosSQL();
        try {
            b.getMaxUniversitario();
        } catch (SQLException e) {
            System.out.println("oi");
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            System.out.println("oi2");
        }
    }//GEN-LAST:event_btn_sobreActionPerformed

    private void btn_AdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdmActionPerformed
        Item_Administrador vis = new Item_Administrador();
        vis.setVisible(true);
    }//GEN-LAST:event_btn_AdmActionPerformed

    private void botao_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ExcluirActionPerformed
        ComandosSQL sql = new ComandosSQL();
        Inicio in = new Inicio();

        int linha = 0, opcao;
        int tabela = 0;

        switch (indiceDeTabela) {
            case 0:
                linha = table_universitario.getSelectedRow();
                tabela = 0;
                System.out.println("\nCódigo selecionado: " + linha + "\nTabela Uni");

                opcao = JOptionPane.showConfirmDialog(null, "Deseja excluir este registro", "Atenção", 1);

                if (opcao == 0) {
                    int cod = Integer.parseInt(String.valueOf(table_universitario.getValueAt(linha, 0)));
                    sql.delete_line_uni(cod);
                    System.out.println("Linha universitarios excluida");
                } else {
                    dispose();
                }

                break;
            case 1:
                linha = table_Projetos.getSelectedRow();
                tabela = 1;
                System.out.println("\nCódigo selecionado: " + linha + "\nTabela Proj");

                opcao = JOptionPane.showConfirmDialog(null, "Deseja excluir este registro", "Atenção", 1);

                if (opcao == 0) {
                    int cod = Integer.parseInt(String.valueOf(table_Projetos.getValueAt(linha, 0)));
                    sql.delete_line_proj(cod);
                    System.out.println("Linha projetos excluida");
                    Tabela.setSelectedIndex(1);
                } else {
                    dispose();
                }

                break;
            case 2:
                linha = table_escola.getSelectedRow();
                tabela = 2;
                System.out.println("\nCódigo selecionado: " + linha + "\nTabela Inv");

                opcao = JOptionPane.showConfirmDialog(null, "Deseja excluir este registro", "Atenção", 1);

                if (opcao == 0) {
                    int cod = Integer.parseInt(String.valueOf(table_escola.getValueAt(linha, 0)));
                    sql.delete_line_inv(cod);
                    System.out.println("Linha inventario excluida");
                    Tabela.setSelectedIndex(2);
                } else {
                    dispose();
                }

                break;
            case 3:
                linha = table_Folgas.getSelectedRow();
                tabela = 3;
                System.out.println("\nCódigo selecionado: " + linha + "\nTabela Fol");

                opcao = JOptionPane.showConfirmDialog(null, "Deseja excluir este registro", "Atenção", 1);

                if (opcao == 0) {
                    int cod = Integer.parseInt(String.valueOf(table_Folgas.getValueAt(linha, 0)));
                    sql.delete_line_folga(cod);
                    System.out.println("Linha folga excluida");
                    in.btn_uniActionPerformed(evt);
                } else {
                    dispose();
                }

                break;
            default:
                break;
        }
        limpar_tabela();
        in.btn_uniActionPerformed(evt);

    }//GEN-LAST:event_botao_ExcluirActionPerformed

    private void botao_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_EditarActionPerformed
        int linha = 0;
        int tabela = 0;
        switch (indiceDeTabela) {
            case 0:
                linha = table_universitario.getSelectedRow();
                tabela = 0;
                System.out.println("\nCódigo selecionado: " + linha + "\nTabela Uni");
                break;
            case 1:
                linha = table_Projetos.getSelectedRow();
                tabela = 1;
                System.out.println("\nCódigo selecionado: " + linha + "\nTabela Pro");
                break;
            case 2:
                linha = table_escola.getSelectedRow();
                tabela = 2;
                System.out.println("\nCódigo selecionado: " + linha + "\nTabela Inv");
                break;
            case 3:
                linha = table_Folgas.getSelectedRow();
                tabela = 3;
                System.out.println("\nCódigo selecionado: " + linha + "\nTabela Folg");
                break;
            default:
                break;
        }
        System.out.println("OK");
        if (tabela == 0) {
            String cod = String.valueOf(table_universitario.getValueAt(linha, 0));
            String nome = String.valueOf(table_universitario.getValueAt(linha, 1));
            String login = String.valueOf(table_universitario.getValueAt(linha, 2));
            String nasc = String.valueOf(table_universitario.getValueAt(linha, 3));
            String dia = String.valueOf(table_universitario.getValueAt(linha, 4));
            
            Edit_Universitario uni = new Edit_Universitario(cod, nome, login, nasc, dia);
            uni.setVisible(true);
        } else if (tabela == 1) {
            int cod = Integer.parseInt(String.valueOf(table_Projetos.getValueAt(linha, 0)));
            String nome = String.valueOf(table_Projetos.getValueAt(linha, 1));
            String organizador = String.valueOf(table_Projetos.getValueAt(linha, 2));
            String inicio = String.valueOf(table_Projetos.getValueAt(linha, 3));
            String fim = String.valueOf(table_Projetos.getValueAt(linha, 4));

            Edit_Projeto proj = new Edit_Projeto(cod, nome, organizador, inicio, fim);
            proj.setVisible(true);
        } else if (tabela == 2) {
            int cod = Integer.parseInt(String.valueOf(table_escola.getValueAt(linha, 0)));
            String descricao = String.valueOf(table_escola.getValueAt(linha, 1));
            String quantidade = String.valueOf(table_escola.getValueAt(linha, 2));
            String medida = String.valueOf(table_escola.getValueAt(linha, 3));
            String modificacao = String.valueOf(table_escola.getValueAt(linha, 4));

            Edit_Inventario inv = new Edit_Inventario(cod, descricao, quantidade, medida, modificacao);
            inv.setVisible(true);
        } else if (tabela == 3) {
            int cod = Integer.parseInt(String.valueOf(table_Folgas.getValueAt(linha, 0)));
            String nome = String.valueOf(table_Folgas.getValueAt(linha, 1));
            String data = String.valueOf(table_Folgas.getValueAt(linha, 2));
            String inclusao = String.valueOf(table_Folgas.getValueAt(linha, 3));

            Edit_Folga fol = null;
            try {
                fol = new Edit_Folga(cod, nome, data, inclusao);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            fol.setVisible(true);

            System.out.println("OK2");
        }


    }//GEN-LAST:event_botao_EditarActionPerformed

    private void table_universitarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_universitarioMouseClicked
        //Se clicar duas vezes, habilita a classe Edit_row para editar o registro
        if (evt.getClickCount() == 2 && Double_Clik == false) {
            int codigo = table_universitario.getSelectedRow();
            System.out.println("\nCódigo selecionado: " + codigo);

            String id = String.valueOf(table_universitario.getValueAt(codigo, 0));

            try {
                Add_Universitario uni = new Add_Universitario(id);
                uni.setVisible(true);
            } catch (SQLException | ClassNotFoundException | ParseException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_table_universitarioMouseClicked

    private void table_ProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ProjetosMouseClicked
        //Se clicar duas vezes, habilita a classe Edit_row para editar o registro
        if (evt.getClickCount() == 2 && Double_Clik == false) {
            int codigo = table_Projetos.getSelectedRow();
            System.out.println("\nCódigo selecionado: " + codigo);

            int cod = Integer.parseInt(String.valueOf(table_Projetos.getValueAt(codigo, 0)));
            String nome = String.valueOf(table_Projetos.getValueAt(codigo, 1));
            String login = String.valueOf(table_Projetos.getValueAt(codigo, 2));
            String nasc = String.valueOf(table_Projetos.getValueAt(codigo, 3));
            String dia = String.valueOf(table_Projetos.getValueAt(codigo, 4));

            Edit_Projeto editar = new Edit_Projeto(cod, nome, login, nasc, dia);
            editar.setVisible(true);
        }
    }//GEN-LAST:event_table_ProjetosMouseClicked

    private void table_escolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_escolaMouseClicked
        //Se clicar duas vezes, habilita a classe Edit_row para editar o registro
        if (evt.getClickCount() == 2 && Double_Clik == false) {
            int codigo = table_escola.getSelectedRow();
            System.out.println("\nCódigo selecionado: " + codigo);

            int cod = Integer.parseInt(String.valueOf(table_escola.getValueAt(codigo, 0)));
            String descricao = String.valueOf(table_escola.getValueAt(codigo, 1));
            String qntd = String.valueOf(table_escola.getValueAt(codigo, 2));
            String medida = String.valueOf(table_escola.getValueAt(codigo, 3));
            String data = String.valueOf(table_escola.getValueAt(codigo, 4));

            Edit_Inventario editar = new Edit_Inventario(cod, descricao, qntd, medida, data);
            editar.setVisible(true);
        }
    }//GEN-LAST:event_table_escolaMouseClicked

    private void table_FolgasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_FolgasMouseClicked
        //Se clicar duas vezes, habilita a classe Edit_row para editar o registro
        if (evt.getClickCount() == 2 && Double_Clik == false) {
            int codigo = table_Folgas.getSelectedRow();
            System.out.println("\nCódigo selecionado: " + codigo);
            int cod = Integer.parseInt(String.valueOf(table_Folgas.getValueAt(codigo, 0)));
            String nome = String.valueOf(table_Folgas.getValueAt(codigo, 1));
            String data = String.valueOf(table_Folgas.getValueAt(codigo, 2));
            String inclusao = String.valueOf(table_Folgas.getValueAt(codigo, 3));

            Edit_Folga editar = null;
            try {
                editar = new Edit_Folga(cod, nome, data, inclusao);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
            editar.setVisible(true);
        }
    }//GEN-LAST:event_table_FolgasMouseClicked

    private void btn_uniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uniActionPerformed
        indiceDeTabela = 0;
        
        Habilitar_Tabelas(0);
        table_universitario.setVisible(true);

        if (pesquisa == true) {
            rs = comandos.getUniv_search(nomePesquisa);

            try {
                while (rs.next()) {
                    uni_id = rs.getString("ID");
                    uni_nome = rs.getString("UNI");
                    uni_dia = rs.getString("DIA");
                    uni_escola = rs.getString("ESCOLA");
                    uni_faculdade = rs.getString("FACULDADE");
                    
                    //valor, linha, coluna
                    table_universitario.setValueAt(uni_id, i, 0);
                    table_universitario.setValueAt(uni_nome, i, 1);
                    table_universitario.setValueAt(uni_dia, i, 2);
                    table_universitario.setValueAt(uni_escola, i, 3);
                    table_universitario.setValueAt(uni_faculdade, i, 4);
                    
                    i++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            rs = comandos.getUniv();

            try {
                while (rs.next()) {
                    uni_id = rs.getString("ID");
                    uni_nome = rs.getString("UNI");
                    uni_dia = rs.getString("DIA");
                    uni_escola = rs.getString("ESCOLA");
                    uni_faculdade = rs.getString("FACULDADE");
                    
                    //valor, linha, coluna
                    table_universitario.setValueAt(uni_id, i, 0);
                    table_universitario.setValueAt(uni_nome, i, 1);
                    table_universitario.setValueAt(uni_dia, i, 2);
                    table_universitario.setValueAt(uni_escola, i, 3);
                    table_universitario.setValueAt(uni_faculdade, i, 4);
                    
                    i++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_uniActionPerformed

    private void btn_projActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_projActionPerformed
        indiceDeTabela = 1;
        
        Habilitar_Tabelas(1);
        table_Projetos.setVisible(true);
        
        ResultSet rs = comandos.getProj();

        int i = 0;
        try {
            while (rs.next()) {
                proj_id = rs.getString("ID");
                proj_nome = rs.getString("NOME");
                proj_organizador = rs.getString("UNI");
                proj_inicio = formatData(rs.getDate("INI"));
                proj_fim = formatData(rs.getDate("FIM"));
                //valor, linha, coluna
                table_Projetos.setValueAt(proj_id, i, 0);
                table_Projetos.setValueAt(proj_nome, i, 1);
                table_Projetos.setValueAt(proj_organizador, i, 2);
                table_Projetos.setValueAt(proj_inicio, i, 3);
                table_Projetos.setValueAt(proj_fim, i, 4);
                i++;

            }
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_projActionPerformed

    private void btn_escolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escolaActionPerformed
        indiceDeTabela = 2;
        
        Habilitar_Tabelas(2);
        table_escola.setVisible(true);
        
        ResultSet rs = comandos.getEscola();
        int i = 0;

        try {
            while (rs.next()) {
                codigo = rs.getString("ID");
                nome = rs.getString("NOME");
                coordenador = rs.getString("COORDENADOR");
                //valor, linha, coluna
                table_escola.setValueAt(codigo, i, 0);
                table_escola.setValueAt(nome, i, 1);
                table_escola.setValueAt(coordenador, i, 2);
                i++;

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro de SQL: " + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_escolaActionPerformed

    private void btn_folActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_folActionPerformed
        indiceDeTabela = 3;
        
        Habilitar_Tabelas(3);
        table_Folgas.setVisible(true);
        
        rs = comandos.getFol();
        i = 0;
        try {
            while (rs.next()) {
                folga_id = rs.getString("ID");
                folga_iduni = rs.getString("UNI");
                folga_escola = rs.getString("ESCOLA");
                folga_data = formatData(rs.getDate("FOLGA"));
                folga_inclusao = formatData(rs.getDate("INCLUSAO"));
                //valor, linha, coluna
                table_Folgas.setValueAt(folga_id, i, 0);
                table_Folgas.setValueAt(folga_iduni, i, 1);
                table_Folgas.setValueAt(folga_escola, i, 2);
                table_Folgas.setValueAt(folga_data, i, 3);
                table_Folgas.setValueAt(folga_inclusao, i, 4);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_folActionPerformed

    private void btn_add_uniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_uniActionPerformed
        try {
            new Add_Universitario();
        } catch (ParseException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_add_uniActionPerformed

    private void btn_add_faculActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_faculActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_faculActionPerformed

    private void btn_add_projActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_projActionPerformed
        Add_Projeto add_proj = null;
        try {
            add_proj = new Add_Projeto();
        } catch (ParseException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        add_proj.setVisible(true);
    }//GEN-LAST:event_btn_add_projActionPerformed

    private void btn_add_folgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_folgaActionPerformed
        Add_Folgas add_folga = null;
        try {
            add_folga = new Add_Folgas();
        } catch (ParseException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        add_folga.setVisible(true);
    }//GEN-LAST:event_btn_add_folgaActionPerformed

    public void limpar_tabela() {
        for (int linha = 0; linha < 30; linha++) {
            for (int coluna = 0; coluna < 5; coluna++) {
                table_universitario.setValueAt(null, linha, coluna);
            }
        }
        for (int linha = 0; linha < 30; linha++) {
            for (int coluna = 0; coluna < 5; coluna++) {
                table_Projetos.setValueAt(null, linha, coluna);
            }
        }
        for (int linha = 0; linha < 30; linha++) {
            for (int coluna = 0; coluna < 5; coluna++) {
                table_escola.setValueAt(null, linha, coluna);
            }
        }
        for (int linha = 0; linha < 30; linha++) {
            for (int coluna = 0; coluna < 4; coluna++) {
                table_Folgas.setValueAt(null, linha, coluna);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });

    }
    
    public void Habilitar_Tabelas(int i){
        
        Tabela.setEnabledAt(0, false);         //Habilita a aba 0
        Tabela.setEnabledAt(1, false);        //Desabilita a aba 1
        Tabela.setEnabledAt(2, false);        //Desabilita a aba 2
        Tabela.setEnabledAt(3, false);        //Desabilita a aba 3
        Tabela.setEnabledAt(4, false);        //Desabilita a aba 4
        Tabela.setEnabledAt(5, false);        //Desabilita a aba 5
        
        Tabela.setSelectedIndex(i);           //Foca na aba 0
        Tabela.setEnabledAt(i, true);         //Habilita a aba 0
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabela;
    private javax.swing.JButton botao_Adicionar;
    private javax.swing.JButton botao_Editar;
    private javax.swing.JButton botao_Excluir;
    private javax.swing.JButton botao_Pesquisar;
    private javax.swing.JButton botao_Salvar;
    private javax.swing.JMenuItem btn_Adm;
    private javax.swing.JMenuItem btn_add_coord;
    private javax.swing.JMenuItem btn_add_escola;
    private javax.swing.JMenuItem btn_add_facul;
    private javax.swing.JMenuItem btn_add_folga;
    private javax.swing.JMenuItem btn_add_proj;
    private javax.swing.JMenuItem btn_add_uni;
    private javax.swing.JMenuItem btn_calend;
    private javax.swing.JMenuItem btn_coord;
    private javax.swing.JMenuItem btn_escola;
    private javax.swing.JMenuItem btn_facul;
    private javax.swing.JMenuItem btn_fol;
    private javax.swing.JMenuItem btn_proj;
    private javax.swing.JMenuItem btn_senha;
    private javax.swing.JMenuItem btn_sobre;
    private javax.swing.JMenuItem btn_uni;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable table_Folgas;
    private javax.swing.JTable table_Projetos;
    private javax.swing.JTable table_escola;
    private javax.swing.JTable table_universitario;
    // End of variables declaration//GEN-END:variables
}
