/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import DB.MySQL;
import Interface.Inicio;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 30-90042
 */
public class Login extends javax.swing.JFrame {

    MySQL db = new MySQL("localhost", "iescola", "root", "");
    String query;
    int result;
    int user_validate = 0;

    /**
     * Creates new form Inicio
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        
        label_fundo.add(botao_entrar);
        label_fundo.add(botao_sair);
        label_fundo.add(txt_user);
        label_fundo.add(txt_password);

        botao_entrar.setBounds(295, 253, 110, 30);
        botao_sair.setBounds(420, 253, 110, 30);
        txt_user.setBounds(356, 184, 189, 25);
        txt_password.setBounds(356, 215, 189, 25);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        botao_entrar = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        txt_user = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        label_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setIconImage(new
            ImageIcon(getClass().getResource("/Imagens/icone.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        botao_entrar.setText("Entrar");
        botao_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 100, -1));

        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 100, -1));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 180, -1));

        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 180, -1));

        label_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Login.jpg"))); // NOI18N
        getContentPane().add(label_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrarActionPerformed
        String usuario_user, usuario_senha;

        usuario_user = txt_user.getText();
        usuario_senha = txt_password.getText();

        if (db.connect()) {

            System.out.println("Conectado!");
            System.out.println("Rodando uma query contra o banco");

            query = "SELECT * FROM COORDENADORES WHERE USR = '" + usuario_user + "' AND PWD = '" + usuario_senha + "'";
            System.out.println(query);
            ResultSet rs = db.executar(query);

            try {
                if (rs != null) {
                    // Verifica se a query retornou algo
                    while (rs.next()) {
                        if ((usuario_user.equals(rs.getString(1))) && (usuario_senha.equals(rs.getString(2)))) {
                            System.out.println("Entrou");
                            user_validate = 1;
                        } else {
                            System.out.println("não Entrou");
                            user_validate = 0;
                        }
                    }
                } else {
                    user_validate = 0;
                }

                if (user_validate == 1) {
                    dispose();
                    Inicio i = new Inicio();
                    i.Inicio();
                } else {
                    JOptionPane.showMessageDialog(null, "User not validate !");
                    user_validate = 0;
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }

        };


    }//GEN-LAST:event_botao_entrarActionPerformed

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botao_sairActionPerformed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            //Toolkit.getDefaultToolkit().beep();
            botao_entrarActionPerformed(null);
        }

    }//GEN-LAST:event_txt_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_entrar;
    private javax.swing.JButton botao_sair;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_fundo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
